spring.datasource.url=${jdbc:postgresql://dpg-d7flvc1f9bms73ejkorg-a:5432/emergency_db_7gmt}
spring.datasource.username=${emergency_db_7gmt_user}
spring.datasource.password=${g19C0wkY112QFZZFozA8ov9RxMrxh6gA}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=admin123

server.port=${PORT:8082}